<?php

/**
 * BaseEntries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property string $photo
 * @property clob $story
 * @property string $image_url
 * @property boolean $auth_publish
 * @property boolean $auth_contact
 * @property boolean $notify_publish
 * @property boolean $approved
 * @property enum $source
 * 
 * @method string  getName()           Returns the current record's "name" value
 * @method string  getEmail()          Returns the current record's "email" value
 * @method string  getPhoto()          Returns the current record's "photo" value
 * @method clob    getStory()          Returns the current record's "story" value
 * @method string  getImageUrl()       Returns the current record's "image_url" value
 * @method boolean getAuthPublish()    Returns the current record's "auth_publish" value
 * @method boolean getAuthContact()    Returns the current record's "auth_contact" value
 * @method boolean getNotifyPublish()  Returns the current record's "notify_publish" value
 * @method boolean getApproved()       Returns the current record's "approved" value
 * @method enum    getSource()         Returns the current record's "source" value
 * @method Entries setName()           Sets the current record's "name" value
 * @method Entries setEmail()          Sets the current record's "email" value
 * @method Entries setPhoto()          Sets the current record's "photo" value
 * @method Entries setStory()          Sets the current record's "story" value
 * @method Entries setImageUrl()       Sets the current record's "image_url" value
 * @method Entries setAuthPublish()    Sets the current record's "auth_publish" value
 * @method Entries setAuthContact()    Sets the current record's "auth_contact" value
 * @method Entries setNotifyPublish()  Sets the current record's "notify_publish" value
 * @method Entries setApproved()       Sets the current record's "approved" value
 * @method Entries setSource()         Sets the current record's "source" value
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntries extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entries');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'email' => true,
             'length' => 255,
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('story', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('image_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('auth_publish', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('auth_contact', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('notify_publish', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('approved', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('source', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'YOUTUBE',
              1 => 'TWITTER',
              2 => 'DIRECT',
             ),
             'default' => 'DIRECT',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}