<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/01 11:01:39
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_a_page_cache_enabled' => false,
  'app_a_search_hard_limit' => 500,
  'app_a_fasthydrate' => true,
  'app_a_routes_register' => false,
  'app_a_default_on' => true,
  'app_a_pretty_english_dates' => true,
  'app_a_credit' => true,
  'app_a_pager_nb_links' => 5,
  'app_a_persistent_global_toolbar' => true,
  'app_a_global_button_order' => array (
  0 => 'blog',
  1 => 'events',
  2 => 'media',
  3 => 'categories',
  4 => 'tags',
  5 => 'users',
  6 => 'reorganize',
),
  'app_a_i18n_switch' => true,
  'app_a_i18n_languages' => array (
  0 => 'en',
  1 => 'fr',
  2 => 'de',
  3 => 'es',
  4 => 'ru',
),
  'app_a_manage_candidate_group' => 'editor',
  'app_a_manage_sufficient_group' => 'admin',
  'app_a_edit_candidate_group' => 'editor',
  'app_a_edit_sufficient_group' => 'admin',
  'app_a_view_locked_sufficient_credentials' => 'view_locked',
  'app_a_use_bundled_layout' => false,
  'app_a_title_prefix' => 'Apostrophe Sandbox | ',
  'app_a_title_suffix' => '',
  'app_a_templates' => array (
  'a' => 
  array (
    'default' => 'Default Page',
    'home' => 'Home Page',
  ),
  'aMedia' => 
  array (
    'default' => 'Media',
  ),
  'aBlog' => 
  array (
    'default' => 'Blog',
  ),
  'aEvent' => 
  array (
    'default' => 'Events',
  ),
),
  'app_a_slot_types' => array (
  'aBlog' => 'Blog Posts',
  'aBlogSingle' => 'Blog Post',
  'aEvent' => 'Events',
  'aEventSingle' => 'Event',
  'aInsetImage' => 'Inset Image',
  'aInsetArea' => 'Inset Area',
  'aBlogSlideshow' => 'Blog Slideshow',
  'aMap' => 'Map',
),
  'app_a_slot_variants' => array (
  'aSlideshow' => 
  array (
    'normal' => 
    array (
      'label' => 'Normal',
      'options' => 
      array (
        'arrows' => true,
      ),
    ),
    'autoplay' => 
    array (
      'label' => 'Autoplay',
      'options' => 
      array (
        'interval' => 4,
        'arrows' => false,
      ),
    ),
  ),
  'aInsetArea' => 
  array (
    'topLeft' => 
    array (
      'label' => 'Left Aligned',
      'options' => 
      array (
        'insetTemplate' => 'topLeft',
      ),
    ),
    'topRight' => 
    array (
      'label' => 'Right Aligned',
      'options' => 
      array (
        'insetTemplate' => 'topRight',
      ),
    ),
  ),
  'aInsetImage' => 
  array (
    'topLeft' => 
    array (
      'label' => 'Left Aligned',
      'options' => 
      array (
        'insetTemplate' => 'topLeft',
      ),
    ),
    'topRight' => 
    array (
      'label' => 'Right Aligned',
      'options' => 
      array (
        'insetTemplate' => 'topRight',
      ),
    ),
  ),
),
  'app_a_addslot_button_style' => 'big',
  'app_a_history_button_style' => 'no-label big',
  'app_a_delete_button_style' => 'no-label',
  'app_a_asset_group' => 'global',
  'app_a_use_bundled_stylesheets' => array (
  'reset' => '/apostrophePlugin/css/a-reset.less',
  'admin' => '/apostrophePlugin/css/a-admin.less',
  'forms' => '/apostrophePlugin/css/a-forms.less',
  'components' => '/apostrophePlugin/css/a-components.less',
  'engines' => '/apostrophePlugin/css/a-engines.less',
  'area-slots' => '/apostrophePlugin/css/a-area-slots.less',
  'buttons' => '/apostrophePlugin/css/a-buttons.less',
  'colors' => '/apostrophePlugin/css/a-colors.less',
  'utility' => '/apostrophePlugin/css/a-utility.less',
),
  'app_a_minify' => true,
  'app_a_minify_gzip' => false,
  'app_a_less_check_dependencies' => false,
  'app_aAdmin_web_dir' => '/apostrophePlugin',
  'app_aMedia_client_apikey' => 'dummy',
  'app_aMedia_apikeys' => array (
  0 => 'dummy',
),
  'app_aMedia_apipublic' => false,
  'app_aMedia_admin_credential' => 'media_admin',
  'app_aMedia_upload_credential' => 'media_upload',
  'app_aMedia_use_bundled_layout' => false,
  'app_aMedia_embed_codes' => true,
  'app_aEvents_display_calendar' => true,
  'app_aBlog_link_author' => true,
  'app_aFeedback_email_auto' => 'apostrophe@punkave.com',
  'app_aFeedback_email_manual' => 'apostrophe@punkave.com',
  'app_aToolkit_indexes' => array (
  0 => 'aPage',
  1 => 'aMediaItem',
),
  'app_aToolkit_allowed_tags' => array (
  0 => 'h3',
  1 => 'h4',
  2 => 'h5',
  3 => 'h6',
  4 => 'blockquote',
  5 => 'p',
  6 => 'a',
  7 => 'ul',
  8 => 'ol',
  9 => 'nl',
  10 => 'li',
  11 => 'b',
  12 => 'i',
  13 => 'strong',
  14 => 'em',
  15 => 'strike',
  16 => 'code',
  17 => 'hr',
  18 => 'br',
  19 => 'div',
  20 => 'table',
  21 => 'thead',
  22 => 'caption',
  23 => 'tbody',
  24 => 'tfoot',
  25 => 'tr',
  26 => 'th',
  27 => 'td',
  28 => 'pre',
  29 => 'dl',
  30 => 'dd',
  31 => 'dt',
),
  'app_aToolkit_allowed_attributes' => array (
  'a' => 
  array (
    0 => 'href',
    1 => 'name',
    2 => 'target',
    3 => 'class',
    4 => 'style',
  ),
  'img' => 
  array (
    0 => 'src',
    1 => 'class',
    2 => 'style',
  ),
  'th' => 
  array (
    0 => 'colspan',
    1 => 'style',
    2 => 'width',
  ),
  'td' => 
  array (
    0 => 'colspan',
    1 => 'style',
    2 => 'width',
  ),
  'table' => 
  array (
    0 => 'align',
    1 => 'class',
    2 => 'style',
    3 => 'width',
  ),
  'ul' => 
  array (
    0 => 'class',
    1 => 'style',
    2 => 'type',
  ),
  'ol' => 
  array (
    0 => 'class',
    1 => 'style',
    2 => 'start',
    3 => 'type',
  ),
  'blockquote' => 
  array (
    0 => 'class',
    1 => 'style',
  ),
  'p' => 
  array (
    0 => 'class',
    1 => 'style',
  ),
),
  'app_aToolkit_allowed_styles' => array (
  'a' => 
  array (
    0 => 'margin',
    1 => 'margin-left',
    2 => 'margin-right',
  ),
  'img' => 
  array (
    0 => 'margin',
    1 => 'margin-left',
    2 => 'margin-right',
  ),
  'td' => 
  array (
    0 => 'margin',
    1 => 'margin-left',
    2 => 'margin-right',
  ),
  'table' => 
  array (
    0 => 'margin',
    1 => 'margin-left',
    2 => 'margin-right',
    3 => 'width',
  ),
  'ul' => 
  array (
    0 => 'margin',
    1 => 'margin-left',
    2 => 'margin-right',
    3 => 'list-style-type',
  ),
  'ol' => 
  array (
    0 => 'margin',
    1 => 'margin-left',
    2 => 'margin-right',
    3 => 'list-style-type',
  ),
  'blockquote' => 
  array (
    0 => 'margin',
    1 => 'margin-left',
    2 => 'margin-right',
  ),
  'p' => 
  array (
    0 => 'margin',
    1 => 'margin-left',
    2 => 'margin-right',
  ),
),
  'app_sfSyncContent_content' => array (
  0 => 'web/uploads',
  1 => 'data/a_writable',
),
  'app_aimageconverter_path' => '/opt/local/bin',
));
