<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/08/01 12:36:23
$this->security = array (
  'redirect' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'blog_author',
        1 => 'admin',
      ),
    ),
  ),
);
