<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/01 09:51:56
sfConfig::add(array(
  'mod_aslideshowslot_enabled' => true,
  'mod_aslideshowslot_view_class' => 'sfPHP',
));
