<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/01 10:34:36
sfConfig::add(array(
  'mod_asmartslideshowslot_enabled' => true,
  'mod_asmartslideshowslot_view_class' => 'sfPHP',
));
