Entries:
  columns:
    name: {type: string(255), notnull: true}
    email: {type: string(255), notnull:true, email:true}
    photo: {type: string(255)}
    story: {type: clob, notnull: true}
    image_url: {type: string(255)}
    auth_publish: {type: boolean, notnull: true}
    auth_contact: {type: boolean}
    notify_publish: {type: boolean}
    approved: {type: boolean}
    source: {type: enum, values:[YOUTUBE, TWITTER, DIRECT], default: DIRECT }
  actAs:
    Timestampable: ~